#!/usr/bin/env bash
set -euo pipefail

TARGET_FILE="${1:-/etc/checklist-app/checklist-app.env}"
TARGET_DIR="$(dirname "${TARGET_FILE}")"

mkdir -p "${TARGET_DIR}"

cat > "${TARGET_FILE}" <<EOF
DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN:-}
DISCORD_CHANNEL_ID=${DISCORD_CHANNEL_ID:-}

CHECKLIST_AWS_REGION=${CHECKLIST_AWS_REGION:-us-west-2}
CHECKLIST_TABLE_NAME=${CHECKLIST_TABLE_NAME:-Checklist}
MATCH_DATA_TABLE_NAME=${MATCH_DATA_TABLE_NAME:-MatchData}

CHECKLIST_CSV_DIRECTORY=${CHECKLIST_CSV_DIRECTORY:-/opt/checklist-app/checklist_csvs}
CHECKLIST_LOG_DIRECTORY=${CHECKLIST_LOG_DIRECTORY:-/var/log/checklist-app}
CHECKLIST_DISPLAY_TIMEZONE=${CHECKLIST_DISPLAY_TIMEZONE:-US/Eastern}

CHECKLIST_MONITOR_POLL_SECONDS=${CHECKLIST_MONITOR_POLL_SECONDS:-300}
CHECKLIST_PER_MATCH_SLEEP_MIN_SECONDS=${CHECKLIST_PER_MATCH_SLEEP_MIN_SECONDS:-3}
CHECKLIST_PER_MATCH_SLEEP_MAX_SECONDS=${CHECKLIST_PER_MATCH_SLEEP_MAX_SECONDS:-8}
CHECKLIST_ROUND_SLEEP_MIN_SECONDS=${CHECKLIST_ROUND_SLEEP_MIN_SECONDS:-40}
CHECKLIST_ROUND_SLEEP_MAX_SECONDS=${CHECKLIST_ROUND_SLEEP_MAX_SECONDS:-50}

CHECKLIST_FOTMOB_WAIT_TIMEOUT_SECONDS=${CHECKLIST_FOTMOB_WAIT_TIMEOUT_SECONDS:-20}
CHECKLIST_FOTMOB_CHROME_BINARY=${CHECKLIST_FOTMOB_CHROME_BINARY:-/snap/chromium/current/usr/lib/chromium-browser/chrome}
CHECKLIST_FOTMOB_CHROMEDRIVER_PATH=${CHECKLIST_FOTMOB_CHROMEDRIVER_PATH:-/snap/chromium/current/usr/lib/chromium-browser/chromedriver}
EOF

chmod 600 "${TARGET_FILE}"

echo "Wrote ${TARGET_FILE}"
